"""GENERATED by koala. Flow id: summarize. Flow version: 0.1.0.

DO NOT EDIT — regenerate via ``Flow.deploy_to_airflow()`` or
``AirflowExecutor.deploy()``.

Task-time logic (argument resolution, action loading, dispatch) lives in
:func:`koala.orchestration.airflow_runtime.run_step` — bumping the koala
package version picks up runtime improvements without needing to
regenerate this file.

Per-step Airflow overrides (pool, queue, priority_weight, retry_delay,
callback refs) are read from ``step["airflow"]`` in the spec at parse
time — see :func:`koala.orchestration.airflow.spec_from_flow` for the
schema. Callback refs are late-imported here so a broken callback module
never breaks DAG parsing.
"""

from __future__ import annotations

import importlib
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

# Airflow 3.x prefers `airflow.sdk`; 2.x uses `airflow.decorators`.
try:
    from airflow.sdk import dag  # Airflow 3
except ImportError:  # pragma: no cover
    from airflow.decorators import dag  # Airflow 2

# PythonOperator moved to the standard provider in Airflow 3.
try:
    from airflow.providers.standard.operators.python import PythonOperator
except ImportError:  # pragma: no cover
    from airflow.operators.python import PythonOperator

from koala.orchestration.airflow_runtime import load_spec, run_step

_DAG_FILE = Path(__file__).resolve()
_SPEC_PATH = str(_DAG_FILE.parent / "koala_specs" / "summarize.json")


def _import_callback(ref: str) -> Any:
    """Late-import a ``module:attribute`` callback ref. Never fails at
    parse time — a bad ref just falls back to ``None`` so the DAG still
    imports and the operator runs with no callback.
    """
    if not isinstance(ref, str) or ":" not in ref:
        return None
    module_name, attr_name = ref.split(":", 1)
    try:
        return getattr(importlib.import_module(module_name), attr_name, None)
    except ImportError:
        return None


def _step_operator_kwargs(step: dict[str, Any]) -> dict[str, Any]:
    """Fold the step's spec + optional Airflow overrides into
    PythonOperator kwargs. Absent fields are left unset (Airflow uses its
    own default_args or built-in defaults).
    """
    kwargs: dict[str, Any] = {
        "task_id": step["id"],
        "python_callable": run_step,
        "op_kwargs": {
            "spec_path": _SPEC_PATH,
            "step_id": step["id"],
        },
    }
    retries = step.get("retries")
    if isinstance(retries, int) and retries > 0:
        kwargs["retries"] = retries
    timeout = step.get("timeout")
    if isinstance(timeout, (int, float)) and timeout > 0:
        kwargs["execution_timeout"] = timedelta(seconds=float(timeout))

    overrides = step.get("airflow") or {}
    for key in ("pool", "queue"):
        if key in overrides:
            kwargs[key] = overrides[key]
    if "pool_slots" in overrides:
        kwargs["pool_slots"] = overrides["pool_slots"]
    if "priority_weight" in overrides:
        kwargs["priority_weight"] = overrides["priority_weight"]
    if "retry_delay_seconds" in overrides:
        kwargs["retry_delay"] = timedelta(
            seconds=float(overrides["retry_delay_seconds"])
        )
    for cb_key, op_key in (
        ("on_failure_callback_ref", "on_failure_callback"),
        ("on_success_callback_ref", "on_success_callback"),
        ("on_retry_callback_ref", "on_retry_callback"),
    ):
        if cb_key in overrides:
            cb = _import_callback(overrides[cb_key])
            if cb is not None:
                kwargs[op_key] = cb
    return kwargs


@dag(
    dag_id='koala_summarize',
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['koala'],
    default_args={'owner': 'koala', 'depends_on_past': False},
    description="Generated by koala for flow 'summarize'.",
)
def _koala_flow() -> None:
    """DAG factory. Called once at parse time."""
    spec = load_spec(_SPEC_PATH)
    tasks: dict[str, PythonOperator] = {}
    # Deterministic ordering so the grid view is stable across parses.
    for step in sorted(spec["steps"], key=lambda s: s["id"]):
        tasks[step["id"]] = PythonOperator(**_step_operator_kwargs(step))
    for from_id, to_id in spec["edges"]:
        tasks[from_id] >> tasks[to_id]


_koala_flow()
